"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var index_1 = require("./utils/index");
var index_2 = require("./events/index");
var index_3 = require("./async/index");
var index_4 = require("./format/index");
var index_5 = require("./xhr/index");
var index_6 = require("./promise/index");
var index_7 = require("./object/index");
index_1.default['async'] = index_3.default;
index_1.default['events'] = index_2.default;
index_1.default['format'] = index_4.default;
index_1.default['xhr'] = index_5.default;
index_1.default['promise'] = index_6.default;
index_1.default['object'] = index_7.default;
exports.default = index_1.default;
